POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0b21wMiIsImlkIjoiNWZiZDUwODRkMzFmMzY2YzA4Mjg0NjlkIiwiaWF0IjoxNjA2MzA3NDY0fQ.BO20i9gAFyVGjVCOZIMzuo7lpT2innm9cCH1CSzHJ0M

{
  "title": "whatever",
  "url": "example.com",
  "likes": 0
}